import keyMirror from "keymirror";

const actionTypes = {
  FETCH_TODO_REQUEST: null,
  FETCH_TODO_SUCCESS: null,
  FETCH_TODO_FAILURE: null,
  SAMPLE_ACTION: null,
  ACTIONS: null,
  FETCH_IDENTITY: null,
  FETCH_IDENTITY_SUCCESS: null,
  FETCH_IDENTITY_FAILURE: null,
  FETCH_TEST_DETAILS: null,
  FETCH_TEST_DETAILS_SUCCESS: null,
  FETCH_TEST_DETAILS_FAILURE: null,
  FETCH_SERVER_TIME_REQUEST: null,
  FETCH_SERVER_TIME_SUCCESS: null,
  FETCH_SERVER_TIME_FAILURE: null,

  PROBLEM_DETAILS_REQUEST: null,
  PROBLEM_DETAILS_SUCCESS: null,
  PROBLEM_DETAILS_FAILURE: null,

  FETCH_QUESTIONS_REQUEST: null,
  FETCH_QUESTIONS_SUCCESS: null,
  FETCH_QUESTIONS_FAILURE: null,

  DELETE_ANSWER_REQUEST: null,
  DELETE_ANSWER_SUCCESS: null,
  DELETE_ANSWER_FAILURE: null,

  DELETE_FIB_REQUEST: null,
  DELETE_FIB_SUCCESS: null,
  DELETE_FIB_FAILURE: null,

  FETCH_PROBLEM_REQUEST: null,
  FETCH_PROBLEM_SUCCESS: null,
  FETCH_PROBLEM_FAILURE: null,

  POST_TEST_REQUEST: null,
  POST_TEST_SUCCESS: null,
  POST_TEST_FAILURE: null,

  FETCH_SINGLE_PRB_SOL_REQUEST: null,
  FETCH_SINGLE_PRB_SOL_SUCCESS: null,
  FETCH_SINGLE_MCQ_SOL_FAILURE: null,

  POST_SINGLE_PRB_SOL_REQUEST: null,
  POST_SINGLE_PRB_SOL_SUCCESS: null,
  POST_SINGLE_PRB_SOL_FAILURE: null,

  POST_FEEDBACk_REQUEST: null,
  POST_FEEDBACK_SUCCESS: null,
  POST_FEEDBACK_FAILURE: null,

  FETCH_SOLUTIONSET_REQUEST: null,
  FETCH_SOLUTIONSET_SUCCESS: null,
  FETCH_SOLUTIONSET_FAILURE: null,

  PATCH_FIB_REQUEST: null,
  PATCH_FIB_REQUEST_SUCCESS: null,
  PATCH_FIB_REQUEST_FAILURE: null,

  POST_REPORT_ISSUE_REQUEST: null,
  POST_REPORT_ISSUE_SUCCESS: null,
  POST_REPORT_ISSUE_FAILURE: null,

  PATCH_ANSWER_REQUEST: null,
  PATCH_ANSWER_REQUEST_SUCCESS: null,
  PATCH_ANSWER_REQUEST_FAILURE: null,

  POST_UPLOAD_FILE_REQUEST: null,
  POST_UPLOAD_FILE_SUCCESS: null,
  POST_UPLOAD_FILE_FAILURE: null,

  POST_SECTION_REQUEST: null,
  POST_SECTION_SUCCESS: null,
  POST_SECTION_FAILURE: null,

  GET_LANGUAGE_REQUEST: null,
  GET_LANGUAGE_SUCCESS: null,
  GET_LANGUAGE_FAILURE: null,

  RUN_CODE_CUSTOM_INPUT_REQUEST: null,
  RUN_CODE_CUSTOM_INPUT_SUCCESS: null,
  RUN_CODE_CUSTOM_INPUT_FAILURE: null,

  RUN_CODE_CUSTOM_INPUT_RESULT: null,

  TESTCASES_RUN_CODE__REQUEST: null,
  TESTCASES_RUN_CODE__SUCCESS: null,
  TESTCASES_RUN_CODE__FAILURE: null,
};

export default keyMirror(actionTypes);
