export const data: any = [
  [
    {
      Language: "Assembler 32 (Mars 4.5)",
      Version: "Mars 4.5",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 10,
      "Libraries available": null,
    },
    {
      Language: "BASH",
      Version: "4.3.11",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 4,
      "Libraries available": null,
    },
    {
      Language: "C",
      Version: "gcc 4.8.2, C99 standard",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 2,
      "Libraries available": ["JSON", "Math Lib"],
    },
    {
      Language: "C++",
      Version: "g++ 4.8.4, C++11 standard",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 2,
      "Libraries available": ["JSON", "Math Lib"],
    },
    {
      Language: "C#",
      Version: "Mono Compiler 4.2.1",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 5,
      "Libraries available": null,
    },
    {
      Language: "Clojure",
      Version: "1.6.0",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 8,
      "Libraries available": null,
    },
    {
      Language: "CommonLisp",
      Version: "GNU CLISP 2.49",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 12,
      "Libraries available": null,
    },
    {
      Language: "Erlang",
      Version: "Erlang/OTP 24 [erts-12.0.2]",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 12,
      "Libraries available":
        "Your module should be named as 'solution' and it should export a method named 'start'",
    },
    {
      Language: "Elixir",
      Version: "Elixir 1.12.0 (compiled with Erlang/OTP 24)",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 12,
      "Libraries available":
        "You must invoke your method at the end of the script",
    },
    {
      Language: "F#",
      Version: "F# Compiler for F# 4.0, Mono 4.2.1",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 5,
      "Libraries available": null,
    },
    {
      Language: "Go",
      Version: "1.5.3",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 4,
      "Libraries available": null,
    },
    {
      Language: "Haskell",
      Version: "7.6.3",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 5,
      "Libraries available": null,
    },
    {
      Language: "Java 7",
      Version: "1.7.0_72",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 10,
      "Libraries available":
        "json-simple\n <strong>Note</strong>: Use 'Source' as class name for java program",
    },
    {
      Language: "Java 8",
      Version: "1.8.0_25",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 10,
      "Libraries available":
        "json-simple\n <strong>Note</strong>: Use 'Source' as class name for java program",
    },
    {
      Language: "JavaScript",
      Version: "Node.js 8.1.4",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 10,
      "Libraries available": null,
    },
    {
      Language: "Julia",
      Version: "0.3.7",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 4,
      "Libraries available": null,
    },
    {
      Language: "Lua",
      Version: "5.2.3",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 12,
      "Libraries available": null,
    },
    {
      Language: "Objective-C",
      Version: "Clang 3.4",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 2,
      "Libraries available": null,
    },
    {
      Language: "PHP",
      Version: "5.5.9-1",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 9,
      "Libraries available": null,
    },
    {
      Language: "Perl",
      Version: "v5.18.2",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 9,
      "Libraries available": null,
    },
    {
      Language: "Python 2",
      Version: "2.7.13",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 10,
      "Libraries available": [
        "requests 2.12.0",
        "simplejson 3.10.0",
        "numpy 1.11.2",
        "scipy 0.18.0",
        "scikit-learn 0.18",
        "matplotlib 1.5.3",
        "cython 0.25.2",
        "pandas 0.19.0",
        "nltk 3.2",
        "pydataset 0.2",
        "imbalanced-learn",
        "seaborn 0.8",
        "statsmodels 0.8",
      ],
    },
    {
      Language: "Python 3",
      Version: "3.4.0",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 10,
      "Libraries available": [
        "requests  2.12.0",
        "simplejson 3.10.0",
        "numpy 1.11.2",
        "scipy 0.18.0",
        "scikit-learn 0.18",
        "matplotlib 1.5.3",
        "cython 0.25.2",
        "pandas 0.19.0",
        "nltk 3.2",
        "pydataset 0.2",
        "imbalanced-learn",
        "seaborn 0.8",
        "statsmodels 0.8",
      ],
    },
    {
      Language: "R",
      Version: "3.0.2",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 10,
      "Libraries available": [
        "RCurl",
        "dplyr",
        "tidyr",
        "readr",
        "stringr",
        "plyr",
        "reshape2",
        "lubridate",
        "data.table",
        "dtplyr",
        "foreach",
        "ggplot2",
        "RColorBrewer",
        "randomForest",
        "rpart",
        "ROCR",
        "car",
        "party",
        "caret",
        "mlr",
        "tree",
        "klaR",
        "ipred",
        "lars",
        "penalized",
        "mlbench",
        "e1071",
        "sqldf",
        "glmnet",
        "gbm",
        "knitr",
        "ggthemes",
        "ggmap",
        "gridExtra",
        "xgboost",
        "tm",
        "wordcloud2",
        "dummies",
        "mice",
        "forecast",
        "naivebayes",
        "caTools",
        "h2o",
        "ggpubr",
        "arules",
        "animation",
        "png",
        "arulesViz",
      ],
    },
    {
      Language: "Ruby",
      Version: "1.9.3p484",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 10,
      "Libraries available": null,
    },
    {
      Language: "Rust",
      Version: "1.5.0",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 5,
      "Libraries available": null,
    },
    {
      Language: "Scala",
      Version: "2.11.4",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 7,
      "Libraries available": null,
    },
    {
      Language: "Swift",
      Version: "4.0.2",
      "Memory limit (in MB)": 512,
      "Time limit (in seconds)": 5,
      "Libraries available": null,
    },
  ],
];
